# Generated by Django 5.0.1 on 2024-01-15 02:24

import image_optimizer.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cabinet_notifications_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='cabinet_notifications_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='cabinet_notifications_frequency',
            field=models.CharField(choices=[('fast', 'As fast as possible'), ('hour', 'Every hour'), ('day', 'Every day'), ('week', 'Every week'), ('month', 'Every month')], default='fast', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='project_notifications_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='project_notifications_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='project_notifications_frequency',
            field=models.CharField(choices=[('fast', 'As fast as possible'), ('hour', 'Every hour'), ('day', 'Every day'), ('week', 'Every week'), ('month', 'Every month')], default='fast', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='users/user/avatar/'),
        ),
    ]
