# Generated by Django 4.2.9 on 2024-02-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_color_user_color1_user_color2_user_color3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
