# Generated by Django 4.2.9 on 2024-02-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_quote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
