# Generated by Django 4.2.9 on 2024-02-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_referral_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points_referral',
            field=models.FloatField(default=0),
        ),
    ]
