# Generated by Django 4.2.9 on 2024-02-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_points_alter_user_points_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='points_referral',
            field=models.FloatField(default=0),
        ),
    ]
