# Generated by Django 4.2.9 on 2024-02-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_referral_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_quote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
