# Generated by Django 4.2.9 on 2024-02-24 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_points_alter_user_points_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters, start from letter, and have length between 4 and 16 characters.', regex='^[A-Za-z]{1}[\\w.@+-]{4,15}\\Z$')]),
        ),
    ]
