# Generated by Django 4.2.9 on 2024-02-24 17:53

import apps.users.validators
import django.core.validators
from django.db import migrations, models
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='users/user/avatar/', validators=[apps.users.validators.avatar_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters, start from letter, and have length between 4 and 16 characters.', regex='^[A-Za-z]{1}[\\w.@+-]{4,15}\\Z$'), apps.users.validators.username_forbidden_validator]),
        ),
    ]
