# Generated by Django 4.2.9 on 2024-03-27 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_avatar_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='points_referral',
            new_name='points_referrer',
        ),
    ]
