# Generated by Django 4.2.9 on 2024-03-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_rename_points_referral_user_points_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='points_referrer',
            field=models.IntegerField(default=0),
        ),
    ]
