# Generated by Django 4.2.9 on 2024-04-24 13:32

import apps.users.validators
import django.core.validators
from django.db import migrations, models
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_user_points_alter_user_points_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_as_nft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_nft',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='users/user/avatar/', validators=[apps.users.validators.avatar_validator]),
        ),
        migrations.AddField(
            model_name='user',
            name='username_as_domain_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='username_domain_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters, start from letter, and have length between 4 and 16 characters.', regex='^[A-Za-z]{1}[\\w.@+-]{4,15}\\Z$'), apps.users.validators.username_forbidden_validator]),
        ),
    ]
