# Generated by Django 5.0.1 on 2024-01-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_socialaccounttelegramcodes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialAccountTelegramCodes',
            new_name='SocialAccountTelegramCode',
        ),
    ]
