# Generated by Django 4.2.9 on 2024-02-11 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reward', models.PositiveIntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TweetWatchVideoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reward', models.PositiveIntegerField()),
                ('link_tweet', models.URLField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitter_tweet_watch_video', to='tasks.projectproxy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TweetRepostTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reward', models.PositiveIntegerField()),
                ('link_tweet', models.URLField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitter_tweet_repost', to='tasks.projectproxy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TweetLikeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reward', models.PositiveIntegerField()),
                ('link_tweet', models.URLField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitter_tweet_like', to='tasks.projectproxy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TweetCommentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reward', models.PositiveIntegerField()),
                ('link_tweet', models.URLField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitter_tweet_comment', to='tasks.projectproxy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TweetCommentExactTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reward', models.PositiveIntegerField()),
                ('link_tweet', models.URLField()),
                ('text', models.TextField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitter_tweet_comment_exact', to='tasks.projectproxy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileFollowTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reward', models.PositiveIntegerField()),
                ('link_prorile', models.URLField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitter_profile_follow', to='tasks.projectproxy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
