# Generated by Django 4.2.9 on 2024-02-11 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_initial'),
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweettask',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitter_tweet', to='tasks.projectproxy'),
        ),
    ]
