# Generated by Django 4.2.9 on 2024-03-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskcustomlog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='taskcustomlog',
            name='got',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskcustomlog',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
