# Generated by Django 4.2.9 on 2024-03-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_project', '0002_alter_taskcustomlog_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcustom',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
