# Generated by Django 4.2.9 on 2024-04-20 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
                ('time_base_of_game', models.PositiveIntegerField(verbose_name='Base time of game (hours)')),
                ('time_increase', models.PositiveIntegerField(verbose_name='Increase time (hours)')),
                ('win_count', models.PositiveIntegerField(verbose_name='Win first')),
                ('type_prize', models.CharField(max_length=32)),
                ('type_distribution', models.CharField(max_length=32)),
                ('base_coin', models.CharField(max_length=8)),
                ('start_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeasonParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('season', 'user')},
            },
        ),
    ]
