# Generated by Django 4.2.9 on 2024-04-20 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_alter_season_start_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeWl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='seasons/prize/image/')),
                ('whitelist_name', models.CharField(max_length=128)),
                ('whitelist_count', models.PositiveIntegerField()),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seasons.season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrizeNft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='seasons/prize/image/')),
                ('collection_name', models.CharField(max_length=128)),
                ('collection_link', models.URLField()),
                ('nft_number', models.PositiveIntegerField()),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seasons.season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrizeCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='seasons/prize/image/')),
                ('coin_ticker', models.CharField(max_length=64)),
                ('coin_count', models.FloatField()),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seasons.season')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
