# Generated by Django 4.2.9 on 2024-03-29 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskSettings',
        ),
    ]
