# Generated by Django 4.2.9 on 2024-02-11 18:42

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0002_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.project',),
        ),
    ]
