# Generated by Django 4.2.9 on 2024-02-17 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_platformtasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformTasksSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_social_reward', models.PositiveIntegerField(default=0)),
                ('task_social_is_active', models.BooleanField()),
                ('task_email_reward', models.PositiveIntegerField(default=0)),
                ('task_email_is_active', models.BooleanField()),
                ('task_username_reward', models.PositiveIntegerField(default=0)),
                ('task_username_is_active', models.BooleanField()),
                ('task_domain_id_reward', models.PositiveIntegerField(default=0)),
                ('task_domain_id_is_active', models.BooleanField()),
                ('task_avatar_reward', models.PositiveIntegerField(default=0)),
                ('task_avatar_is_active', models.BooleanField()),
                ('task_nft_avatar_reward', models.PositiveIntegerField(default=0)),
                ('task_nft_avatar_is_active', models.BooleanField()),
                ('task_ursas_collection_nft_avatar_reward', models.PositiveIntegerField(default=0)),
                ('task_ursas_collection_nft_avatar_is_active', models.BooleanField()),
                ('task_wallet_reward', models.PositiveIntegerField(default=0)),
                ('task_wallet_is_active', models.BooleanField()),
                ('task_chain_reward', models.PositiveIntegerField(default=0)),
                ('task_chain_is_active', models.BooleanField()),
                ('task_referral_reward', models.PositiveIntegerField(default=0)),
                ('task_referral_is_active', models.BooleanField()),
                ('task_email_notification_reward', models.PositiveIntegerField(default=0)),
                ('task_email_notification_is_active', models.BooleanField()),
                ('task_cabinet_notification_reward', models.PositiveIntegerField(default=0)),
                ('task_cabinet_notification_is_active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Platform Tasks settings',
            },
        ),
        migrations.CreateModel(
            name='TaskUsernameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('got', models.BooleanField()),
                ('reward', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PlatformTasks',
        ),
    ]
