# Generated by Django 4.2.9 on 2024-02-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_platformtaskssettings_taskusernamelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_username_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
