# Generated by Django 4.2.9 on 2024-02-17 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0007_platformtaskssettings_cancel_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformtaskssettings',
            old_name='task_social_reward',
            new_name='task_social_discord_reward',
        ),
        migrations.RemoveField(
            model_name='platformtaskssettings',
            name='task_social_is_active',
        ),
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_social_discord_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_social_github_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_social_github_reward',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_social_telegram_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_social_telegram_reward',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_social_x_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_social_x_reward',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_avatar_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_cabinet_notification_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_chain_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_domain_id_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_email_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_email_notification_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_nft_avatar_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_referral_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_ursas_collection_nft_avatar_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_username_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_wallet_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskusernamelog',
            name='got',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TaskEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('got', models.BooleanField(default=False)),
                ('reward', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
