# Generated by Django 4.2.9 on 2024-02-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_rename_task_social_reward_platformtaskssettings_task_social_discord_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_referral_self_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_referral_self_reward',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
