# Generated by Django 4.2.9 on 2024-02-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_platformtaskssettings_task_referral_self_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_avatar_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_cabinet_notification_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_domain_id_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_email_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_email_notification_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_nft_avatar_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_referral_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_referral_self_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_social_discord_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_social_github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_social_telegram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_social_x_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_ursas_collection_nft_avatar_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformtaskssettings',
            name='task_wallet_link',
            field=models.BooleanField(default=False),
        ),
    ]
