# Generated by Django 4.2.9 on 2024-02-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_platformtaskssettings_task_avatar_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformtaskssettings',
            name='task_referral_is_active',
        ),
        migrations.RemoveField(
            model_name='platformtaskssettings',
            name='task_referral_link',
        ),
        migrations.RemoveField(
            model_name='platformtaskssettings',
            name='task_referral_reward',
        ),
        migrations.RemoveField(
            model_name='platformtaskssettings',
            name='task_referral_title',
        ),
    ]
