# Generated by Django 4.2.9 on 2024-02-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_platformtaskssettings_task_referral_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_cabinet_notification_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_chain_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_email_notification_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_nft_avatar_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_referral_self_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_ursas_collection_nft_avatar_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_wallet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
