# Generated by Django 4.2.9 on 2024-02-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_platformtaskssettings_task_cabinet_notification_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_avatar_link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_cabinet_notification_link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_chain_link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_domain_id_link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_email_link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_email_notification_link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_nft_avatar_link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_referral_self_link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_social_discord_link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_social_github_link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_social_telegram_link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_social_x_link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_ursas_collection_nft_avatar_link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_username_link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='platformtaskssettings',
            name='task_wallet_link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
