# Generated by Django 4.2.9 on 2024-02-18 21:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0016_taskwalletlog_taskursascollectionnftavatarlog_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskCabinetNotificationLog',
            new_name='TaskAccountNotificationLog',
        ),
        migrations.RenameField(
            model_name='platformtaskssettings',
            old_name='task_cabinet_notification_is_active',
            new_name='task_account_notification_is_active',
        ),
        migrations.RenameField(
            model_name='platformtaskssettings',
            old_name='task_cabinet_notification_link',
            new_name='task_account_notification_link',
        ),
        migrations.RenameField(
            model_name='platformtaskssettings',
            old_name='task_cabinet_notification_reward',
            new_name='task_account_notification_reward',
        ),
        migrations.RenameField(
            model_name='platformtaskssettings',
            old_name='task_cabinet_notification_title',
            new_name='task_account_notification_title',
        ),
    ]
