# Generated by Django 4.2.9 on 2024-02-19 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_rename_taskcabinetnotificationlog_taskaccountnotificationlog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformtaskssettings',
            old_name='task_account_notification_is_active',
            new_name='task_avatar_nft_is_active',
        ),
        migrations.RenameField(
            model_name='platformtaskssettings',
            old_name='task_account_notification_link',
            new_name='task_avatar_nft_link',
        ),
        migrations.RenameField(
            model_name='platformtaskssettings',
            old_name='task_account_notification_reward',
            new_name='task_avatar_nft_reward',
        ),
        migrations.RenameField(
            model_name='platformtaskssettings',
            old_name='task_account_notification_title',
            new_name='task_avatar_nft_title',
        ),
        migrations.RenameField(
            model_name='platformtaskssettings',
            old_name='task_email_notification_is_active',
            new_name='task_avatar_nft_ursas_is_active',
        ),
        migrations.RenameField(
            model_name='platformtaskssettings',
            old_name='task_email_notification_link',
            new_name='task_avatar_nft_ursas_link',
        ),
        migrations.RenameField(
            model_name='platformtaskssettings',
            old_name='task_email_notification_reward',
            new_name='task_avatar_nft_ursas_reward',
        ),
        migrations.RenameField(
            model_name='platformtaskssettings',
            old_name='task_email_notification_title',
            new_name='task_avatar_nft_ursas_title',
        ),
        migrations.RenameField(
            model_name='platformtaskssettings',
            old_name='task_nft_avatar_is_active',
            new_name='task_cabinet_notification_account_is_active',
        ),
        migrations.RenameField(
            model_name='platformtaskssettings',
            old_name='task_nft_avatar_link',
            new_name='task_cabinet_notification_account_link',
        ),
        migrations.RenameField(
            model_name='platformtaskssettings',
            old_name='task_nft_avatar_reward',
            new_name='task_cabinet_notification_account_reward',
        ),
        migrations.RenameField(
            model_name='platformtaskssettings',
            old_name='task_nft_avatar_title',
            new_name='task_cabinet_notification_account_title',
        ),
        migrations.RenameField(
            model_name='platformtaskssettings',
            old_name='task_ursas_collection_nft_avatar_is_active',
            new_name='task_cabinet_notification_email_is_active',
        ),
        migrations.RenameField(
            model_name='platformtaskssettings',
            old_name='task_ursas_collection_nft_avatar_link',
            new_name='task_cabinet_notification_email_link',
        ),
        migrations.RenameField(
            model_name='platformtaskssettings',
            old_name='task_ursas_collection_nft_avatar_reward',
            new_name='task_cabinet_notification_email_reward',
        ),
        migrations.RenameField(
            model_name='platformtaskssettings',
            old_name='task_ursas_collection_nft_avatar_title',
            new_name='task_cabinet_notification_email_title',
        ),
    ]
