# Generated by Django 4.2.9 on 2024-02-19 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_platformtasklog_remove_taskavatarlog_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlatformTasksSettings',
            new_name='PlatformTaskSettings',
        ),
    ]
