# Generated by Django 4.2.9 on 2024-02-19 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0020_rename_platformtaskssettings_platformtasksettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformtasklog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='platformtasklog',
            unique_together={('user', 'task')},
        ),
    ]
