# Generated by Django 4.2.9 on 2024-02-20 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_alter_platformtasklog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformtasklog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 2, 20, 19, 32, 28, 295873, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
