# Generated by Django 4.2.9 on 2024-02-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_platformtasklog_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformtasksettings',
            name='referral_quote',
            field=models.PositiveIntegerField(default=0, verbose_name='Task cancel fee (%)'),
        ),
    ]
