# Generated by Django 4.2.9 on 2024-02-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_platformtasksettings_referral_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformtasksettings',
            name='referral_comission',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platformtasksettings',
            name='referral_quote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
