# Generated by Django 4.2.9 on 2024-02-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_platformtasksettings_referral_comission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformtasksettings',
            name='referral_comission',
            field=models.PositiveIntegerField(default=0, verbose_name='Referral comission (%)'),
        ),
    ]
