# Generated by Django 4.2.9 on 2024-02-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_alter_platformtasksettings_referral_comission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformtasksettings',
            name='task_domain_id_is_active',
        ),
        migrations.RemoveField(
            model_name='platformtasksettings',
            name='task_domain_id_link',
        ),
        migrations.RemoveField(
            model_name='platformtasksettings',
            name='task_domain_id_reward',
        ),
        migrations.RemoveField(
            model_name='platformtasksettings',
            name='task_domain_id_title',
        ),
        migrations.AlterField(
            model_name='platformtasklog',
            name='task',
            field=models.CharField(choices=[('task_social_x', 'Task - connect X account'), ('task_social_github', 'Task - connect GitHub account'), ('task_social_discord', 'Task - connect Discord account'), ('task_social_telegram', 'Task - connect Telegram account'), ('task_email', 'Task - set email'), ('task_username', 'Task - set username'), ('task_avatar', 'Task - set avatar'), ('task_avatar_nft', 'Task - set avatar from NFT'), ('task_avatar_nft_ursas', 'Task - set avatar from NFT by Ursas collection'), ('task_wallet', 'Task - add wallet'), ('task_chain', 'Task - add chain'), ('task_referral_self', 'Task - set referral code'), ('task_cabinet_notification_account', 'Task - enable cabinet account notifications'), ('task_cabinet_notification_email', 'Task - enable cabinet email notifications')], max_length=128),
        ),
    ]
