# Generated by Django 4.2.9 on 2024-02-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_remove_platformtasksettings_task_domain_id_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformtasksettings',
            name='task_username_domain_id_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformtasksettings',
            name='task_username_domain_id_link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='platformtasksettings',
            name='task_username_domain_id_reward',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformtasksettings',
            name='task_username_domain_id_title',
            field=models.CharField(default='Task - set username from domain ID', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platformtasklog',
            name='task',
            field=models.CharField(choices=[('task_social_x', 'Task - connect X account'), ('task_social_github', 'Task - connect GitHub account'), ('task_social_discord', 'Task - connect Discord account'), ('task_social_telegram', 'Task - connect Telegram account'), ('task_email', 'Task - set email'), ('task_username', 'Task - set username'), ('task_username_domain_id', 'Task - set domain id username'), ('task_avatar', 'Task - set avatar'), ('task_avatar_nft', 'Task - set avatar from NFT'), ('task_avatar_nft_ursas', 'Task - set avatar from NFT by Ursas collection'), ('task_wallet', 'Task - add wallet'), ('task_chain', 'Task - add chain'), ('task_referral_self', 'Task - set referral code'), ('task_cabinet_notification_account', 'Task - enable cabinet account notifications'), ('task_cabinet_notification_email', 'Task - enable cabinet email notifications')], max_length=128),
        ),
    ]
