# Generated by Django 4.2.9 on 2024-02-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_rename_task_referral_self_is_active_platformtasksettings_task_referrer_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformtasksettings',
            old_name='task_cabinet_notification_account_is_active',
            new_name='task_cabinet_notifications_account_is_active',
        ),
        migrations.RenameField(
            model_name='platformtasksettings',
            old_name='task_cabinet_notification_account_link',
            new_name='task_cabinet_notifications_account_link',
        ),
        migrations.RenameField(
            model_name='platformtasksettings',
            old_name='task_cabinet_notification_account_reward',
            new_name='task_cabinet_notifications_account_reward',
        ),
        migrations.RenameField(
            model_name='platformtasksettings',
            old_name='task_cabinet_notification_account_title',
            new_name='task_cabinet_notifications_account_title',
        ),
        migrations.RenameField(
            model_name='platformtasksettings',
            old_name='task_cabinet_notification_email_is_active',
            new_name='task_cabinet_notifications_email_is_active',
        ),
        migrations.RenameField(
            model_name='platformtasksettings',
            old_name='task_cabinet_notification_email_link',
            new_name='task_cabinet_notifications_email_link',
        ),
        migrations.RenameField(
            model_name='platformtasksettings',
            old_name='task_cabinet_notification_email_reward',
            new_name='task_cabinet_notifications_email_reward',
        ),
        migrations.RenameField(
            model_name='platformtasksettings',
            old_name='task_cabinet_notification_email_title',
            new_name='task_cabinet_notifications_email_title',
        ),
        migrations.AlterField(
            model_name='platformtasklog',
            name='task',
            field=models.CharField(choices=[('task_social_x', 'Task - connect X account'), ('task_social_github', 'Task - connect GitHub account'), ('task_social_discord', 'Task - connect Discord account'), ('task_social_telegram', 'Task - connect Telegram account'), ('task_email', 'Task - set email'), ('task_username', 'Task - set username'), ('task_username_domain_id', 'Task - set domain id username'), ('task_avatar', 'Task - set avatar'), ('task_avatar_nft', 'Task - set avatar from NFT'), ('task_avatar_nft_ursas', 'Task - set avatar from NFT by Ursas collection'), ('task_wallet', 'Task - add wallet'), ('task_chain', 'Task - add chain'), ('task_referrer', 'Task - set referrer'), ('task_cabinet_notifications_account', 'Task - enable cabinet account notifications'), ('task_cabinet_notifications_email', 'Task - enable cabinet email notifications')], max_length=128),
        ),
    ]
