# Generated by Django 4.2.9 on 2024-02-24 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0030_remove_platformtasksettings_referral_comission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformtasksettings',
            name='referral_genesis_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
