# Generated by Django 4.2.9 on 2024-02-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0002_channelmessageimagetask_channelmessagetask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessageimagetask',
            name='link_channel',
            field=models.URLField(default='https://google.com/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channelmessagetask',
            name='link_channel',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postreactiontask',
            name='link_post',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serverboosttask',
            name='link_server',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serverroletask',
            name='link_server',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serversubscribetask',
            name='link_server',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
    ]
