# Generated by Django 4.2.9 on 2024-02-10 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('discord', '0004_alter_channelmessageimagetask_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmessageimagetask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord_channel_message_image', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='channelmessagetask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord_channel_message', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='postreactiontask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord_channel_reaction', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='serverboosttask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord_server_boost', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='serverroletask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord_server_role', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='serversubscribetask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord_server_subscribe', to='projects.project'),
        ),
    ]
