# Generated by Django 4.2.9 on 2024-02-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0006_alter_channelmessageimagetask_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelmessageimagetask',
            name='image',
        ),
    ]
