# Generated by Django 4.2.9 on 2024-03-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointSystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_fee', models.PositiveIntegerField(default=0, verbose_name='Cancel fee (%)')),
                ('referrer_interest', models.PositiveIntegerField(default=0, verbose_name='Referrer interest (%)')),
            ],
            options={
                'verbose_name': 'Point system settings',
                'verbose_name_plural': 'Point system settings',
            },
        ),
    ]
