"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta


BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = 'django-insecure-$+eyrm&&gge&$jn^jh%n^eess%xuhj$ifqym+i1nxu_#jtxdh='

DEBUG = True

ALLOWED_HOSTS = ['ursasplanet.com', 'api.ursasplanet.com', 'localhost', 'leks.hooli.xyz']
CSRF_TRUSTED_ORIGINS = [
    'https://ursasplanet.com',
    'https://api.ursasplanet.com',
    'http://localhost:3000',
    'http://leks.hooli.xyz:3000']
CORS_ALLOWED_ORIGINS = [
    'https://ursasplanet.com',
    'https://api.ursasplanet.com',
    'http://localhost:3000',
    'http://leks.hooli.xyz:3000'
]
CORS_ORIGIN_WHITELIST = (
    'http://localhost:3000',
    'http://leks.hooli.xyz:3000'
)
CORS_ALLOW_CREDENTIALS = True


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    "corsheaders",
    'image_optimizer',

    'apps.users',
    'apps.projects',
    'apps.wallets',
    'apps.web3auth',
    'apps.socials'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR/'static'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR/'media'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'users.User'


REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.BasicAuthentication',
        'apps.web3auth.authenticate.CustomAuthentication',
    )
}

SIMPLE_JWT = {
    'AUTH_COOKIE': 'access_token',  
    'AUTH_COOKIE_DOMAIN': 'leks.hooli.xyz',     
    'AUTH_COOKIE_SECURE': False,
    'AUTH_COOKIE_HTTP_ONLY' : True, 
    'AUTH_COOKIE_PATH': '/',        
    'AUTH_COOKIE_SAMESITE': 'Lax',  
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60)
}

OPTIMIZED_IMAGE_METHOD = 'pillow'


EMAIL_HOST = 'mail.privateemail.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'support@ursasplanet.com'
EMAIL_HOST_PASSWORD = '8bgX4q9EB6fAUYrQrwis514QSMhw6GrHDcBgonKk6ZP4'
EMAIL_USE_SSL = True


SOCIAL_REDIRECT_URI_PREFIX = 'http://leks.hooli.xyz:3000/settings/?auth='

GITHUB_CLIENT_ID = 'Iv1.ceba5cde6dfa0cb8'
GITHUB_SECRET_KEY = '7673bdcf5aa691f5aff2ecea22ad5e4e4d663e69'
GITHUB_REDIRECT_URI = SOCIAL_REDIRECT_URI_PREFIX + 'github'

DISCORD_CLIENT_ID = '1198777405234499704'
DISCORD_SECRET_KEY = 'y7O2v8zHKKK3UCUB8uYjIT34252PndiY'
DISCORD_REDIRECT_URI = SOCIAL_REDIRECT_URI_PREFIX + 'discord'

X_CLIENT_ID = 'RlA5clc1N3ZMb01uVlVObk5ycFc6MTpjaQ'
X_CLIENT_SECRET = 'yG5LrvQ3Gwz2XzmX6AU7PiM0PBA--4vfL8kTbmwUPVvL496TSa'
X_REDIRECT_URI = SOCIAL_REDIRECT_URI_PREFIX + 'x'

TELEGRAM_BOT_TOKEN = '6505934697:AAErrCETR6czcoo1BRh2lsQO4Buf3fzDUZM'