# Generated by Django 4.2.9 on 2024-03-26 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_username_title', models.CharField(max_length=64)),
                ('task_username_link', models.CharField(blank=True, max_length=64, null=True)),
                ('task_username_reward', models.PositiveIntegerField(default=0)),
                ('task_username_is_active', models.BooleanField(default=False)),
                ('task_email_title', models.CharField(max_length=64)),
                ('task_email_link', models.CharField(blank=True, max_length=64, null=True)),
                ('task_email_reward', models.PositiveIntegerField(default=0)),
                ('task_email_is_active', models.BooleanField(default=False)),
                ('task_avatar_title', models.CharField(max_length=64)),
                ('task_avatar_link', models.CharField(blank=True, max_length=64, null=True)),
                ('task_avatar_reward', models.PositiveIntegerField(default=0)),
                ('task_avatar_is_active', models.BooleanField(default=False)),
                ('task_referrer_title', models.CharField(max_length=64)),
                ('task_referrer_link', models.CharField(blank=True, max_length=64, null=True)),
                ('task_referrer_reward', models.PositiveIntegerField(default=0)),
                ('task_referrer_is_active', models.BooleanField(default=False)),
                ('task_cabinet_notifications_account_title', models.CharField(max_length=64)),
                ('task_cabinet_notifications_account_link', models.CharField(blank=True, max_length=64, null=True)),
                ('task_cabinet_notifications_account_reward', models.PositiveIntegerField(default=0)),
                ('task_cabinet_notifications_account_is_active', models.BooleanField(default=False)),
                ('task_cabinet_notifications_email_title', models.CharField(max_length=64)),
                ('task_cabinet_notifications_email_link', models.CharField(blank=True, max_length=64, null=True)),
                ('task_cabinet_notifications_email_reward', models.PositiveIntegerField(default=0)),
                ('task_cabinet_notifications_email_is_active', models.BooleanField(default=False)),
                ('task_social_discord_title', models.CharField(max_length=64)),
                ('task_social_discord_link', models.CharField(blank=True, max_length=64, null=True)),
                ('task_social_discord_reward', models.PositiveIntegerField(default=0)),
                ('task_social_discord_is_active', models.BooleanField(default=False)),
                ('task_social_github_title', models.CharField(max_length=64)),
                ('task_social_github_link', models.CharField(blank=True, max_length=64, null=True)),
                ('task_social_github_reward', models.PositiveIntegerField(default=0)),
                ('task_social_github_is_active', models.BooleanField(default=False)),
                ('task_social_telegram_title', models.CharField(max_length=64)),
                ('task_social_telegram_link', models.CharField(blank=True, max_length=64, null=True)),
                ('task_social_telegram_reward', models.PositiveIntegerField(default=0)),
                ('task_social_telegram_is_active', models.BooleanField(default=False)),
                ('task_social_x_title', models.CharField(max_length=64)),
                ('task_social_x_link', models.CharField(blank=True, max_length=64, null=True)),
                ('task_social_x_reward', models.PositiveIntegerField(default=0)),
                ('task_social_x_is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tasks',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='PlatformTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('task_username', 'Task - set username'), ('task_email', 'Task - set email'), ('task_avatar', 'Task - set avatar'), ('task_referrer', 'Task - set referrer'), ('task_cabinet_notifications_account', 'Task - enable cabinet account notifications'), ('task_cabinet_notifications_email', 'Task - enable cabinet email notifications'), ('task_social_discord', 'Task - connect Discord account'), ('task_social_github', 'Task - connect Github account'), ('task_social_telegram', 'Task - connect Telegram account'), ('task_social_x', 'Task - connect X account')], max_length=128)),
                ('got', models.BooleanField(default=False)),
                ('reward', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'task')},
            },
        ),
    ]
