# Generated by Django 4.2.9 on 2024-03-27 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='platformtasklog',
            unique_together=set(),
        ),
    ]
