# Generated by Django 5.0.1 on 2024-01-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
