# Generated by Django 5.0.1 on 2024-01-06 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectwallet',
            name='chain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallets.chain'),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='chain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallets.chain'),
        ),
    ]
