# Generated by Django 5.0.1 on 2024-01-19 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters, start from letter, and have length between 4 and 16 characters.', regex='^[A-Za-z][\\w.@+-]{4,15}+\\Z')]),
        ),
    ]
