# Generated by Django 4.2.9 on 2024-02-03 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_useremailcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters, start from letter, and have length between 4 and 16 characters.', regex='^[A-Za-z]{1}[\\w.@+-]{4,15}\\Z$')]),
        ),
    ]
