# Generated by Django 4.2.9 on 2024-03-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0003_rename_socialaccounttelegramcodes_socialaccounttelegramcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccounttelegramcode',
            name='uuid',
            field=models.TextField(unique=True),
        ),
    ]
