# Generated by Django 4.2.9 on 2024-02-11 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_initial'),
        ('github', '0002_alter_profilefollowtask_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefollowtask',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_profile_follow', to='tasks.projectproxy'),
        ),
        migrations.AlterField(
            model_name='repositoryforktask',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_repository_fork', to='tasks.projectproxy'),
        ),
        migrations.AlterField(
            model_name='repositorystartask',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_repository_star', to='tasks.projectproxy'),
        ),
    ]
